### PR TITLE
Updating Resources component

### PR DESCRIPTION
**Pull request by blainehussey**
This PR contains the following updates under the Resources component;

- Add new tile for TTYDA under
- Remove the “Event Stream Concept Maps” tile
- Move the “Developer community” tile one to the left
- Update “Component Concept Maps” to “Best Practice Articles”, with a description of “Articles that provide guidance, examples, or recommendations for how best to use Solace products.” The link remains the same.
- Remove the “Quick Starts” tile as that page doesn’t seem to exist anymore
- Update “Integration Guides” to “Integration Hub” and point it to: https://solace.com/integration-hub/ Description: Your one-stop shop for enabling event-driven integration

### CODE REVIEW

**Comment by blainehussey** [comment]
Hi @Mrc0113 and @TamimiGitHub,
I've made the requested updates to tutorials.solace.dev, in order to add a new tile for the TTYDA initiative, as well the other updated requested to the Resources section. You can view the updates at the following STAGING URL, if all looks good please let me know, so I can merge it to Production.
https://deploy-preview-153--solace-dev-tutorials.netlify.app/

Please review this PR and let me know if I'm missing anything, or if you'd like any further changes.

Thanks again.

**Comment by TamimiGitHub** [comment]
Do we need to keep the integration guides and/or the integration hub? We have the guides in codelabs https://codelabs.solace.dev/?cat=integration

**Comment by blainehussey** [comment]
> Do we need to keep the integration guides and/or the integration hub? We have the guides in codelabs https://codelabs.solace.dev/?cat=integration

Good question @TamimiGitHub, I don't think it can hurt to have it on both sites (.dev and codelabs), but I'll let @Mrc0113 answer this one.

**Comment by Mrc0113** [comment]
@TamimiGitHub @blainehussey let's keep the Integration Hub resource

**Review by Mrc0113 — APPROVED** [review]

**Pull request merged**
